trigger:
- main

pool:
  name: DevOps

variables:
  terraformVersion: '1.9.8'

stages:

#############################################################
# DEV
#############################################################

- stage: DEV
  displayName: "Terraform DEV"

  jobs:

  - job: DevTerraform

    steps:

    - checkout: self

    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: $(terraformVersion)

    #########################
    # INIT
    #########################

    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: azurerm
        command: init
        workingDirectory: $(System.DefaultWorkingDirectory)/Root/Dev

        backendServiceArm: DevSecOPs
        backendAzureRmResourceGroupName: devsecops-rg
        backendAzureRmStorageAccountName: devsecopsstrg
        backendAzureRmContainerName: devsecopcont
        backendAzureRmKey: dev.tfstate



    #########################
    # VALIDATE
    #########################

    - task: TerraformTask@5
      displayName: Terraform Validate
      inputs:
        provider: azurerm
        command: validate
        workingDirectory: $(System.DefaultWorkingDirectory)/Root/Dev

    #########################
    # TFLINT
    #########################

    - script: |
        tflint --init
        tflint
      displayName: TFLint
      workingDirectory: $(System.DefaultWorkingDirectory)/Root/Dev

    #########################
    # TFSEC
    #########################

    - script: |
        tfsec .
      displayName: TFSec
      workingDirectory: $(System.DefaultWorkingDirectory)/Root/Dev

    #########################
    # CHECKOV
    #########################

    - script: |
        checkov -d .
      displayName: Checkov
      workingDirectory: $(System.DefaultWorkingDirectory)/Root/Dev

    #########################
    # PLAN
    #########################

    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: azurerm
        command: plan
        workingDirectory: $(System.DefaultWorkingDirectory)/Root/Dev
        environmentServiceNameAzureRM: DevSecOPs

