trigger:
- main

pool:
  name: DevSecOps

variables:
  serviceConnection: 'DevSecOPs'
  backendStorageAccount: 'devsecopsstrg'
  backendContainer: 'devsecopcont'

###########################################################
# DEV STAGE
###########################################################

stages:

- stage: DEV
  displayName: "Development"

  jobs:

  - job: Terraform_DEV
    displayName: "Terraform DEV"

    steps:

    - checkout: self

    - task: TerraformTask@5
      displayName: "Terraform Init"
      inputs:
        provider: azurerm
        command: init
        workingDirectory: "$(System.DefaultWorkingDirectory)/Root/Dev"
        backendServiceArm: "$(serviceConnection)"
        backendAzureRmStorageAccountName: "$(backendStorageAccount)"
        backendAzureRmContainerName: "$(backendContainer)"
        backendAzureRmKey: "dev.tfstate"

    - script: |
        cd "$(System.DefaultWorkingDirectory)/Root/Dev"
        terraform validate
      displayName: "Terraform Validate"

    - script: |
        cd "$(System.DefaultWorkingDirectory)/Root/Dev"
        terraform fmt -recursive -check
      displayName: "Terraform Format"

    - script: |
        cd "$(System.DefaultWorkingDirectory)/Root/Dev"
        tflint --init
        tflint
      displayName: "TFLint"

    - script: |
        cd "$(System.DefaultWorkingDirectory)/Root/Dev"
        tfsec .
      displayName: "TFSec"

    - script: |
        cd "$(System.DefaultWorkingDirectory)/Root/Dev"
        checkov -d .
      displayName: "Checkov"

    - task: TerraformTask@5
      displayName: "Terraform Plan"
      inputs:
        provider: azurerm
        command: plan
        workingDirectory: "$(System.DefaultWorkingDirectory)/Root/Dev"
        environmentServiceNameAzureRM: "$(serviceConnection)"
        commandOptions: "-out=tfplan"

###########################################################
# QA STAGE
###########################################################

- stage: QA
  displayName: "Quality Assurance"
  dependsOn: DEV
  condition: succeeded()

  jobs:

  - job: Terraform_QA

    steps:

    - checkout: self

    - task: TerraformTask@5
      displayName: "Terraform Init"
      inputs:
        provider: azurerm
        command: init
        workingDirectory: "$(System.DefaultWorkingDirectory)/Root/QA"
        backendServiceArm: "$(serviceConnection)"
        backendAzureRmStorageAccountName: "$(backendStorageAccount)"
        backendAzureRmContainerName: "$(backendContainer)"
        backendAzureRmKey: "qa.tfstate"

    - script: |
        cd "$(System.DefaultWorkingDirectory)/Root/QA"
        terraform validate
      displayName: Validate

    - script: |
        cd "$(System.DefaultWorkingDirectory)/Root/QA"
        terraform fmt -recursive -check
      displayName: Format

    - script: |
        cd "$(System.DefaultWorkingDirectory)/Root/QA"
        tflint
      displayName: TFLint

    - script: |
        cd "$(System.DefaultWorkingDirectory)/Root/QA"
        tfsec .
      displayName: TFSec

    - script: |
        cd "$(System.DefaultWorkingDirectory)/Root/QA"
        checkov -d .
      displayName: Checkov

    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: azurerm
        command: plan
        workingDirectory: "$(System.DefaultWorkingDirectory)/Root/QA"
        environmentServiceNameAzureRM: "$(serviceConnection)"
        commandOptions: "-out=tfplan"

###########################################################
# PROD STAGE
###########################################################

- stage: PROD
  displayName: "Production"
  dependsOn: QA
  condition: succeeded()

  jobs:

  - deployment: Terraform_PROD

    displayName: Terraform PROD

    environment: Production

    strategy:

      runOnce:

        deploy:

          steps:

          - checkout: self

          - task: TerraformTask@5
            displayName: Terraform Init
            inputs:
              provider: azurerm
              command: init
              workingDirectory: "$(System.DefaultWorkingDirectory)/Root/Prod"
              backendServiceArm: "$(serviceConnection)"
              backendAzureRmStorageAccountName: "$(backendStorageAccount)"
              backendAzureRmContainerName: "$(backendContainer)"
              backendAzureRmKey: "prod.tfstate"

          - script: |
              cd "$(System.DefaultWorkingDirectory)/Root/Prod"
              terraform validate
            displayName: Validate

          - script: |
              cd "$(System.DefaultWorkingDirectory)/Root/Prod"
              terraform fmt -recursive -check
            displayName: Format

          - script: |
              cd "$(System.DefaultWorkingDirectory)/Root/Prod"
              tflint
            displayName: TFLint

          - script: |
              cd "$(System.DefaultWorkingDirectory)/Root/Prod"
              tfsec .
            displayName: TFSec

          - script: |
              cd "$(System.DefaultWorkingDirectory)/Root/Prod"
              checkov -d .
            displayName: Checkov

          - task: TerraformTask@5
            displayName: Terraform Plan
            inputs:
              provider: azurerm
              command: plan
              workingDirectory: "$(System.DefaultWorkingDirectory)/Root/Prod"
              environmentServiceNameAzureRM: "$(serviceConnection)"
              commandOptions: "-out=tfplan"

          - task: TerraformTask@5
            displayName: Terraform Apply
            inputs:
              provider: azurerm
              command: apply
              workingDirectory: "$(System.DefaultWorkingDirectory)/Root/Prod"
              environmentServiceNameAzureRM: "$(serviceConnection)"
              commandOptions: "tfplan"