
trigger:
  - main

pool:
  name: DevOps

steps:
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'init'
      workingDirectory: '$(System.DefaultWorkingDirectory)/Root/Dev'
      backendServiceArm: 'DevSecOPs'
      backendAzureRmStorageAccountName: 'devsecopsstrg'
      backendAzureRmContainerName: 'devsecopcont'
      backendAzureRmKey: 'backup.tfstate'
